In [2]:
import numpy as np

np.random.seed(1)

d = {"A ": np.random.binomial(10, 0.5, 5),
     "B" : np.random.binomial(10, 0.3, 5),
     "C" : np.random.binomial(10, 0.6, 5),
     "D" : np.random.binomial(10, 0.4, 5)}

d

{'A ': array([5, 6, 0, 4, 3]),
 'B': array([1, 2, 2, 3, 3]),
 'C': array([6, 5, 7, 4, 9]),
 'D': array([5, 4, 4, 2, 3])}

In [29]:
import pandas as pd

idx = ["Clau", "Esme", "JM", "Isis", "Miguel"]

df = pd.DataFrame(d, index = idx)
df["Promedio"] = df.mean(axis= 1)
df

        A   B  C  D  Promedio
Clau     5  1  6  5      4.25
Esme     6  2  5  4      4.25
JM       0  2  7  4      3.25
Isis     4  3  4  2      3.25
Miguel   3  3  9  3      4.50

In [4]:
df.columns

Index(['A ', 'B', 'C', 'D'], dtype='object')

In [5]:
# Escoger columna(s)
df[["A ", "C"]]

   A   C
0   5  6
1   6  5
2   0  7
3   4  4
4   3  9

In [25]:
# Escoger fila(s)

df.iloc[0:4:2]

   A   B  C  D
1   5  1  6  5
3   0  2  7  4

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
 3   D       5 non-null      int64
dtypes: int64(4)
memory usage: 292.0 bytes

In [8]:
df.describe() # La estadística descriptiva de los datos

             A         B         C         D
count  5.000000  5.00000  5.000000  5.000000
mean   3.600000  2.20000  6.200000  3.600000
std    2.302173  0.83666  1.923538  1.140175
min    0.000000  1.00000  4.000000  2.000000
25%    3.000000  2.00000  5.000000  3.000000
50%    4.000000  2.00000  6.000000  4.000000
75%    5.000000  3.00000  7.000000  4.000000
max    6.000000  3.00000  9.000000  5.000000

In [9]:
df.T

    0  1  2  3  4
A   5  6  0  4  3
B   1  2  2  3  3
C   6  5  7  4  9
D   5  4  4  2  3

In [10]:
type(df["A "])

pandas.core.series.Series

In [11]:
print(df["A "][0])

5

In [12]:
ssma = pd.read_csv("/content/drive/MyDrive/Datos ML/Students Social Media Addiction.csv")
ssma.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

In [13]:
ssma.tail()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5
701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9
702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4
704,705,19,Female,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5,Single,4,8

In [14]:
ssma.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Relationship_Status',
       'Conflicts_Over_Social_Media', 'Addicted_Score'],
      dtype='object')

In [15]:
ssma_1 = ssma[['Age', 'Gender', 'Avg_Daily_Usage_Hours', 'Most_Used_Platform']]
ssma_1

     Age  Gender  Avg_Daily_Usage_Hours Most_Used_Platform
0     19  Female                    5.2          Instagram
1     22    Male                    2.1            Twitter
2     20  Female                    6.0             TikTok
3     18    Male                    3.0            YouTube
4     21    Male                    4.5           Facebook
..   ...     ...                    ...                ...
700   20  Female                    4.7             TikTok
701   23    Male                    6.8          Instagram
702   21  Female                    5.6             WeChat
703   24    Male                    4.3            Twitter
704   19  Female                    6.2           Facebook

[705 rows x 4 columns]

In [16]:
avg = ssma_1[ssma_1['Avg_Daily_Usage_Hours']>4.0]
avg

     Age  Gender  Avg_Daily_Usage_Hours Most_Used_Platform
0     19  Female                    5.2          Instagram
2     20  Female                    6.0             TikTok
4     21    Male                    4.5           Facebook
5     19  Female                    7.2          Instagram
7     20  Female                    5.8           Snapchat
..   ...     ...                    ...                ...
700   20  Female                    4.7             TikTok
701   23    Male                    6.8          Instagram
702   21  Female                    5.6             WeChat
703   24    Male                    4.3            Twitter
704   19  Female                    6.2           Facebook

[536 rows x 4 columns]

In [36]:
ssma_1 = ssma_1.rename(columns={"Hours":"Horas", "Gender":"Sexo",
                                "Platforma": "Plataforma", "Age":"Edad"})

In [40]:
ssma_2 = ssma_1[ssma_1["Horas"] > 4.0]
ssma_2

     Edad    Sexo  Horas Plataforma
0      19  Female    5.2  Instagram
2      20  Female    6.0     TikTok
4      21    Male    4.5   Facebook
5      19  Female    7.2  Instagram
7      20  Female    5.8   Snapchat
..    ...     ...    ...        ...
700    20  Female    4.7     TikTok
701    23    Male    6.8  Instagram
702    21  Female    5.6     WeChat
703    24    Male    4.3    Twitter
704    19  Female    6.2   Facebook

[536 rows x 4 columns]

In [41]:
ssma_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 536 entries, 0 to 704
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Edad        536 non-null    int64
 1   Sexo        536 non-null    object
 2   Horas       536 non-null    float64
 3   Plataforma  536 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 20.9+ KB

In [44]:
group_ssma_2 = ssma_2.groupby(by = "Sexo")["Horas"].max()
group_ssma_2

Sexo
Female    8.5
Male      7.5
Name: Horas, dtype: float64

In [45]:
platform_ssma_2 = ssma_2.groupby(by= "Plataforma")["Horas"].max()
platform_ssma_2

Plataforma
Facebook     7.2
Instagram    8.5
KakaoTalk    5.2
Snapchat     6.1
TikTok       8.4
Twitter      6.3
VKontakte    4.8
WeChat       5.8
WhatsApp     7.5
YouTube      5.8
Name: Horas, dtype: float64

In [46]:
ssma_2.groupby(by="Plataforma")['Horas'].count()

Plataforma
Facebook      82
Instagram    186
KakaoTalk     12
Snapchat      12
TikTok       138
Twitter       28
VKontakte      8
WeChat        13
WhatsApp      54
YouTube        3
Name: Horas, dtype: int64

In [51]:
ssma_3 = ssma_2.groupby("Plataforma")["Horas"].size()
ssma_4 = ssma_3.sort_values(ascending=False)
ssma_4

Plataforma
Instagram    186
TikTok       138
Facebook      82
WhatsApp      54
Twitter       28
WeChat        13
KakaoTalk     12
Snapchat      12
VKontakte      8
YouTube        3
Name: Horas, dtype: int64