# Introduction to SQL

SQL (Structured Query Language, pronounced "sequel" or ess-cue-ell) is a domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS), or for stream processing in a relational data stream management system (RDSMS). It is particularly useful in handling structured data where there are relations between different entities/variables of the data. SQL is a very important tool for data scientists to have in their repertoire.

  A relational database is, simply, a database that stores related information across multiple tables and allows you to query information in more than one table at the same time. Within a table, the data to be stored is organized in a tabular format with rows and columns. Each row inside a table represents a distinct record with the column headings specifying the corresponding type of data stored. Software that is used to manage a digital database is called a Database Management System (DBMS). There are quite a few database systems available (such as MySQL, PostgreSQL, IBM Db2 and Oracle Database, etc.). The Web site DB-Engines collects and presents information on DBMSs and provides a monthly listing of them, ranked by their current popularity. You’ll likely find yourself using many different types of databases throughout your education and work. However, all of them speak SQL, so once you've got the hang of the basic SQL syntax you'll be able to work with any of them.


Advantages of Using SQL (Rahul, 2018)

- It is standardized: no matter which relational database you choose, it will have an SQL query interpreter built in. The sheer popularity of SQL makes it worth everyone’s time who interacts with a data system.

- It has a reasonable English-like syntax: None of the painstaking detail of programming languages like C or Java have to be specified when using SQL. It is concise, easy to understand, and easy to write database queries with. It is declarative in nature, meaning you only have to declare what you want to achieve rather than going over the steps to achieve the results.

- It allows a uniform way to query and administer a relational database: Many of the database administration commands are standard SQL commands making the transfer of skills much easier.

- It is mature: SQL has been around for over 35 years. While many new features have been added to it, the core of SQL has largely been unchanged. You can derive a lot of utility knowing a few basic SQL concepts and commands, and they will serve you well into the future.

In [1]:
import mysql.connector
from mysql.connector import Error

In [2]:
def create_server_connection(host_name, user_name, user_password):
    connection = None
    try:
        connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            passwd=user_password
        )
        print("MySQL Database connection successful")
    except Error as err:
        print(f"Error: '{err}'")

    return connection

pw="Perfeligro"
db="writers"

In [3]:
connection = create_server_connection("localhost", "root", pw)

MySQL Database connection successful

In [22]:
def create_database(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        print("Database created successfully")
    except Error as err:
        print(f"Error: '{err}'")

create_database_query = "CREATE DATABASE writers"
create_database(connection, create_database_query)

Error: '1007 (HY000): Can't create database 'writers'; database exists'

In [5]:
def create_db_connection(host_name, user_name, user_password, db_name):
    connection = None
    try:
        connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            passwd=user_password,
            database=db_name
        )
        print("MySQL Database connection successful")
    except Error as err:
        print(f"Error: '{err}'")

    return connection

In [12]:
def execute_query(connection,query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        connection.commit()
        print("Query successful")
    except Error as err:
        print(f"Error: '{err}' ")

## Creating tables

Now we're all set to start running SQL commands into our Server and to start building our database. The first thing we want to do is to create the necessary tables.

In [23]:
create_writers_table = """
CREATE TABLE writers (
  writer_pos INT,
  Writer VARCHAR(40) NOT NULL,
  Book VARCHAR(40) NOT NULL,
  Language VARCHAR(3) NOT NULL,
  Year INT
  
);
"""


connection = create_db_connection("localhost", "root", pw, db)
execute_query(connection, create_writers_table)

MySQL Database connection successful
Error: '1050 (42S01): Table 'writers' already exists'

In [25]:
pop_writers = """
INSERT INTO writers VALUES
(1, 'JAMES JOYCE', 'Ulises', 'ENG', 1922), 
(2, 'EDGAR ALLAN POE', 'The Raven', 'ENG', 1845), 
(3, 'JUAN RULFO', 'Pedro Paramo', 'ESP', 1955), 
(4, 'GEORGE ORWELL', 'Animal Farm', 'ENG', 1945), 
(5, 'MARY SHELLEY', 'Frankenstein', 'ENG', 1818), 
(6, 'JEAN-JACQUES ROUSSEAU', 'Du contrat social ', 'FRA', 1762), 
(7, 'THOMAS MANN', 'Der Zauberberg', 'GER', 1924), 
(8, 'JULIO VERNE', 'L’Ile mystérieuse', 'ESP', 1875), 
(9, 'TOLSTOI', 'Война и мир', 'RUS', 1869); 

"""

connection = create_db_connection("localhost", "root", pw, db)
execute_query(connection, pop_writers)

MySQL Database connection successful
Query successful

In [26]:
def read_query(connection, query):
    cursor = connection.cursor()
    result = None
    try:
        cursor.execute(query)
        result = cursor.fetchall()
        return result
    except Error as err:
        print(f"Error: '{err}'")

In [27]:
q1 = """
SELECT *
FROM writers;
"""

connection = create_db_connection("localhost", "root", pw, db)
results = read_query(connection, q1)

for result in results:
  print(result)

MySQL Database connection successful
(1, 'JAMES JOYCE', 'Ulises', 'ENG', '1922')
(2, 'EDGAR ALLAN POE', 'The Raven', 'ENG', '1845')
(3, 'JUAN RULFO', 'Pedro Paramo', 'ESP', '1955')
(4, 'GEORGE ORWELL', 'Animal Farm', 'ENG', '1945')
(5, 'MARY SHELLEY', 'Frankenstein', 'ENG', '1818')
(6, 'JEAN-JACQUES ROUSSEAU', 'Du contrat social ', 'FRA', '1762')
(7, 'THOMAS MANN', 'Der Zauberberg', 'GER', '1924')
(8, 'JULIO VERNE', 'L’Ile mystérieuse', 'ESP', '1875')
(9, 'TOLSTOI', 'Война и мир', 'RUS', '1869')

In [28]:
import pandas as pd

from_db = []

for result in results:
  result = list(result)
  from_db.append(result)


columns = ["Position", "Writer", "Oeuvre", "Language", "Year"]
df = pd.DataFrame(from_db, columns=columns)

In [29]:
display(df)

   Position                 Writer              Oeuvre Language  Year
0         1            JAMES JOYCE              Ulises      ENG  1922
1         2        EDGAR ALLAN POE           The Raven      ENG  1845
2         3             JUAN RULFO        Pedro Paramo      ESP  1955
3         4          GEORGE ORWELL         Animal Farm      ENG  1945
4         5           MARY SHELLEY        Frankenstein      ENG  1818
5         6  JEAN-JACQUES ROUSSEAU  Du contrat social       FRA  1762
6         7            THOMAS MANN      Der Zauberberg      GER  1924
7         8            JULIO VERNE   L’Ile mystérieuse      ESP  1875
8         9                TOLSTOI         Война и мир      RUS  1869

In [30]:
df.sort_values(by=['Year'])

   Position                 Writer              Oeuvre Language  Year
5         6  JEAN-JACQUES ROUSSEAU  Du contrat social       FRA  1762
4         5           MARY SHELLEY        Frankenstein      ENG  1818
1         2        EDGAR ALLAN POE           The Raven      ENG  1845
8         9                TOLSTOI         Война и мир      RUS  1869
7         8            JULIO VERNE   L’Ile mystérieuse      ESP  1875
0         1            JAMES JOYCE              Ulises      ENG  1922
6         7            THOMAS MANN      Der Zauberberg      GER  1924
3         4          GEORGE ORWELL         Animal Farm      ENG  1945
2         3             JUAN RULFO        Pedro Paramo      ESP  1955

In [31]:
df.sort_values(by=['Position'], ascending=False)

   Position                 Writer              Oeuvre Language  Year
8         9                TOLSTOI         Война и мир      RUS  1869
7         8            JULIO VERNE   L’Ile mystérieuse      ESP  1875
6         7            THOMAS MANN      Der Zauberberg      GER  1924
5         6  JEAN-JACQUES ROUSSEAU  Du contrat social       FRA  1762
4         5           MARY SHELLEY        Frankenstein      ENG  1818
3         4          GEORGE ORWELL         Animal Farm      ENG  1945
2         3             JUAN RULFO        Pedro Paramo      ESP  1955
1         2        EDGAR ALLAN POE           The Raven      ENG  1845
0         1            JAMES JOYCE              Ulises      ENG  1922

### HOMEWORK

$1.-$ At the beggining of the document, write the following:
- Introduction to SQL.
- 5 examples of its uses in real life. Applications. 
- How can you use SQL in your future studies?
- Include graphics and images.

$2.-$ By using the `sort` methods in Pandas order the data by:
    - name
    - first appeareance
    - Nationality
    - Language

$3.-$ Create a new database based on [Billboard](http://www.billboard.com) and two tables:
a.- Which artists were listened to the most.
b.- Most sold albums in the year.

Write a report in which you explain the following:
- Objective of your database
- The kind of database you chose
- The tables you created, the fields, and their data types
- Where you obtained the information
- How you filled the table
- How the tables will be connected

$4.-$ (Continuation of point $3$) Continue your report writing the findings, discussion, conclusion and recommendations. To obtain the information, you are going to look for at least $10$ artists that are popular in the US.
- Write a program to see the artists ordered from highest to lowest in terms of the number of streams.
- Write a program to see the artists ordered from highest to lowest in terms of the number of sold albums.
- Write a join query to see if there are any artists who are in both lists (streams and sold albums).
- Delete the entries from the artists that they did not find in the join query.